//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoAvto.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cards
    {
        public int id { get; set; }
        public string card_number { get; set; }
        public string cvv_code { get; set; }
        public string card_date { get; set; }
        public int cardtypes_id { get; set; }
        public int user_id { get; set; }
    
        public virtual CardTypes CardTypes { get; set; }
        public virtual Users Users { get; set; }
    }
}
