//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoAvto.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Searches
    {
        public int id { get; set; }
        public string address_start { get; set; }
        public string address_finish { get; set; }
        public double route_time { get; set; }
        public double route_distance { get; set; }
        public System.DateTime time_finish { get; set; }
        public int user_id { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
